### ISSUE TITLE
Niepoprawny plik Makefile

### ISSUE THREAD

**Issue by andrzejwp** [019253166/ProgramowanieObiektowe#1]
Plik `Makefile` jest niepoprawny. Wywołanie polecenia `make` kończy się błędem. 

![image](https://user-images.githubusercontent.com/3079734/78171495-d05c3480-7454-11ea-8f98-0e42c7606cc3.png)

Proszę o poprawienie.

**Comment by 019253166** [comment]
Faktycznie błąd znajdował się w tym miejscu:
main.o : main.cpp
	g++ -c ${FLAGS} -o tablica.o tablica.cpp

Zmieniłem ten fragment na: 
main.o : main.cpp
	g++ -c ${FLAGS} -o main.o main.cpp
Teraz kompiluje się poprawnie
