### ISSUE TITLE
Proszę dodać brakujące pliki struktury do repozytorium

### ISSUE THREAD

**Issue by andrzejwp** [019253166/ProgramowanieObiektowe#3]
https://github.com/019253166/ProgramowanieObiektowe/blob/0d02dfe55f3d1cc8d8998aa3623122601b9a1e24/lab3/main.cpp#L5

**Comment by 019253166** [comment]
Struktura na ten moment znajduje się w pliku `tablica.h`. Czy powinienem stworzyć osobny plik nagłówkowy dla struktury?

**Comment by andrzejwp** [comment]
Jest Ok, dziękuję.
